### ISSUE TITLE
IndexError: Index out of range

### ISSUE THREAD

**Issue by SeekPoint** [liuhuanyong/DocSentimentAnalysis#1]
mldl@ub1604:~/ub16_prj/DocSentimentAnalysis$ python3 test.py 
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.822 seconds.
Prefix dict has been built succesfully.
Postagger: Model not loaded!
Parser: Model not loaded!
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    test()
  File "test.py", line 47, in test
    doc_sentiment_score = handler.doc_sentiment_score(content6)
  File "/home/mldl/ub16_prj/DocSentimentAnalysis/DocSentimentAnalysis.py", line 97, in doc_sentiment_score
    sent_score = self.get_sentence_score(sent_words, senti_words)
  File "/home/mldl/ub16_prj/DocSentimentAnalysis/DocSentimentAnalysis.py", line 62, in get_sentence_score
    sent_tuples = self.senti_parser.syntax_parser(sent_words, sent_postag)
  File "/home/mldl/ub16_prj/DocSentimentAnalysis/sentence_parser.py", line 31, in syntax_parser
    arc_index = arcs[index].head
IndexError: Index out of range

**Comment by SeekPoint** [comment]
why?

**Comment by zhangnew** [comment]
@loveJasmine  在项目根目录创建一个目录 `ltp_data/` ，把 `pyltp` 的模型放进去。
@liuhuanyong 博主在 README 把这段写清楚吧，难道是故意提高门槛吗？

**Comment by SeekPoint** [comment]
@zhangnew thanks
